package promote

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// GitopsPR opens a real PR against the gitops repo:
//
//  1. `gh repo clone` the gitops repo to a tmpdir
//  2. EditApplicationSet on the applicationset.yaml
//  3. git checkout -b <branch>
//  4. git add + git commit + git push -u origin <branch>
//  5. gh pr create --base main --head <branch> ...
//
// Returns the URL of the opened PR. The caller is responsible for
// the snapshot's S3 upload — this struct only handles the gitops PR.
type GitopsPR struct {
	GitopsRepo     string // "owner/name"
	Applicationset string // relative path inside the gitops repo
	SiteKey        string // matrix entry key
	Bucket         string // S3 bucket name (echoed in PR body)
	DefaultBranch  string // base branch for the PR (defaults to "main")

	// Stdout / Stderr receive subprocess output. Stdout is forwarded
	// for git/gh progress; the final PR URL is parsed from gh's
	// stdout independently of this writer.
	Stdout io.Writer
	Stderr io.Writer

	// keepClone preserves the temp clone dir on success — useful for
	// tests; default false (cleanup).
	keepClone bool
}

// Open performs the full clone → edit → commit → push → PR flow.
func (g *GitopsPR) Open(ctx context.Context, env Env, snapshotID, s3Key string) (string, error) {
	if !env.Valid() {
		return "", fmt.Errorf("promote: invalid env %q", env)
	}
	if g.GitopsRepo == "" {
		return "", fmt.Errorf("promote: gitops repo is empty (gitops.repo in frankenpress.toml)")
	}
	if g.Applicationset == "" {
		return "", fmt.Errorf("promote: applicationset path is empty (gitops.applicationset in frankenpress.toml)")
	}

	base := g.DefaultBranch
	if base == "" {
		base = "main"
	}

	stdout, stderr := g.streams()

	clone, err := os.MkdirTemp("", "fp-gitops-")
	if err != nil {
		return "", fmt.Errorf("promote: mktemp: %w", err)
	}
	if !g.keepClone {
		defer os.RemoveAll(clone)
	}

	if err := g.run(ctx, stdout, stderr, "", "gh", "repo", "clone", g.GitopsRepo, clone, "--", "--depth=1", "--branch="+base); err != nil {
		return "", err
	}

	appSetPath := filepath.Join(clone, g.Applicationset)
	original, err := os.ReadFile(appSetPath)
	if err != nil {
		return "", fmt.Errorf("promote: read %s: %w", appSetPath, err)
	}
	edited, err := EditApplicationSet(original, g.SiteKey, SnapshotValues{
		Ref:    snapshotID,
		S3Key:  s3Key,
		Bucket: g.Bucket,
	})
	if err != nil {
		return "", err
	}
	if bytes.Equal(original, edited) {
		return "", fmt.Errorf("promote: applicationset edit produced no diff — already at this snapshot ref?")
	}
	if err := os.WriteFile(appSetPath, edited, 0o644); err != nil {
		return "", fmt.Errorf("promote: write %s: %w", appSetPath, err)
	}

	branch := fmt.Sprintf("fp/promote-%s-%s-%s", g.SiteKey, env, snapshotID)
	commitMsg := fmt.Sprintf("%s(%s): bump snapshot to %s", g.SiteKey, env, snapshotID)

	if err := g.run(ctx, stdout, stderr, clone, "git", "checkout", "-b", branch); err != nil {
		return "", err
	}
	if err := g.run(ctx, stdout, stderr, clone, "git", "add", g.Applicationset); err != nil {
		return "", err
	}
	if err := g.run(ctx, stdout, stderr, clone, "git", "commit", "-m", commitMsg); err != nil {
		return "", err
	}
	if err := g.run(ctx, stdout, stderr, clone, "git", "push", "-u", "origin", branch); err != nil {
		return "", err
	}

	body := g.renderBody(env, snapshotID, s3Key)
	prURL, err := g.runCapture(ctx, stderr, clone,
		"gh", "pr", "create",
		"--repo", g.GitopsRepo,
		"--base", base,
		"--head", branch,
		"--title", commitMsg,
		"--body", body,
	)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(prURL), nil
}

func (g *GitopsPR) renderBody(env Env, snapshotID, s3Key string) string {
	return fmt.Sprintf(`Promote request from fp.

Bumps `+"`siteInstall.snapshot`"+` on the matrix entry `+"`site: %s`"+` in `+"`%s`"+`:

`+"```yaml"+`
snapshot:
  ref:    %s
  s3Key:  %s
  bucket: %s
`+"```"+`

Snapshot blobs already uploaded to `+"`s3://%s/%s`"+`.

Once merged + ArgoCD reconciles, the chart's install Job runs `+"`wp fp apply`"+`, which:

1. Verifies db.sql.gz sha256 against the manifest
2. Imports the SQL via `+"`wp db import`"+`
3. Runs `+"`wp search-replace`"+` to retarget URLs to the env's home_url
4. Fires premium-theme adapter post_restore hooks
5. Stamps `+"`fp_snapshot_applied_ref`"+` + `+"`fp_snapshot_applied_sha256`"+` (idempotent on re-run)

Generated by fp; review the diff before merging.
`,
		g.SiteKey, g.Applicationset, snapshotID, s3Key, g.Bucket, g.Bucket, s3Key)
}

func (g *GitopsPR) streams() (stdout, stderr io.Writer) {
	stdout = g.Stdout
	if stdout == nil {
		stdout = io.Discard
	}
	stderr = g.Stderr
	if stderr == nil {
		stderr = io.Discard
	}
	return
}

func (g *GitopsPR) run(ctx context.Context, stdout, stderr io.Writer, dir, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	if dir != "" {
		cmd.Dir = dir
	}
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("promote: `%s %s`: %w", name, strings.Join(args, " "), err)
	}
	return nil
}

// runCapture is like run, but captures stdout for the caller (used to
// parse the PR URL from `gh pr create`).
func (g *GitopsPR) runCapture(ctx context.Context, stderr io.Writer, dir, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	if dir != "" {
		cmd.Dir = dir
	}
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("promote: `%s %s`: %w", name, strings.Join(args, " "), err)
	}
	return out.String(), nil
}
